#!/bin/bash

# host="10.4.2.27" # old printer
host="10.4.2.222"
port="9100"

echo trying http://$host/

width="$(curl -s http://$host/general/status.html | grep -Po '\d+(?=mm)')"
size="$(($width*160/24))"
size="$(($size<128?$size:128))"
echo "$width" mm tape detected, resizing to "$size"px

convert -background white "$1" -sample x"$size" -gravity center -extent x128 pbm:- | "$(dirname "$(readlink -f "$0")")/ptouch-770-write-stdout" $width | nc $host $port
